# -*- coding: utf-8 -*-
"""Exp-7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I40KXwiFg_mXZiO9KwX-XbxPaLuWV-u6
"""

import pandas as pd
import numpy as nm
# Importing the dataset
dataset = pd.read_csv('user_data.csv')
dataset

x = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)
# Predicting the Test set results
y_pred = classifier.predict(x_test)
y_pred

from sklearn.metrics import  confusion_matrix
cm=nm.array(confusion_matrix(y_test,y_pred))
cm

